SET SERVEROUTPUT ON;

DECLARE
    c_credential CONSTANT VARCHAR2(128) := 'AWS_S3_CRED';
    c_target_uri CONSTANT VARCHAR2(4000) :=
        'https://lslabsessions-adb-s3-lab.s3.eu-central-1.amazonaws.com/outbound/message-generated.txt';

    l_source_clob      CLOB;
    l_generated_clob   CLOB;
    l_upload_blob      BLOB;
    l_returned_blob    BLOB;
    l_returned_clob    CLOB;
    l_dest_offset      PLS_INTEGER;
    l_src_offset       PLS_INTEGER;
    l_lang_context     PLS_INTEGER;
    l_warning          PLS_INTEGER;
    l_compare_result   INTEGER;
BEGIN
    SELECT t.text_content
      INTO l_source_clob
      FROM s3_file_store f
      JOIN s3_file_text t
        ON t.file_id = f.file_id
     WHERE f.file_name = 'message.txt';

    DBMS_LOB.CREATETEMPORARY(l_generated_clob, TRUE);
    DBMS_LOB.APPEND(l_generated_clob, l_source_clob);

    DBMS_LOB.WRITEAPPEND(
        lob_loc => l_generated_clob,
        amount  => LENGTH(CHR(10) || 'Generated by Oracle Autonomous Database.'),
        buffer  => CHR(10) || 'Generated by Oracle Autonomous Database.'
    );

    DBMS_LOB.CREATETEMPORARY(l_upload_blob, TRUE);
    l_dest_offset  := 1;
    l_src_offset   := 1;
    l_lang_context := DBMS_LOB.DEFAULT_LANG_CTX;

    -- Encode characters explicitly as UTF-8 bytes before PUT_OBJECT.
    DBMS_LOB.CONVERTTOBLOB(
        dest_lob     => l_upload_blob,
        src_clob     => l_generated_clob,
        amount       => DBMS_LOB.LOBMAXSIZE,
        dest_offset  => l_dest_offset,
        src_offset   => l_src_offset,
        blob_csid    => NLS_CHARSET_ID('AL32UTF8'),
        lang_context => l_lang_context,
        warning      => l_warning
    );

    DBMS_OUTPUT.PUT_LINE('Generated CLOB length : ' || DBMS_LOB.GETLENGTH(l_generated_clob) || ' characters');
    DBMS_OUTPUT.PUT_LINE('UTF-8 BLOB size       : ' || DBMS_LOB.GETLENGTH(l_upload_blob) || ' bytes');
    DBMS_OUTPUT.PUT_LINE('Encoding warning      : ' || l_warning);

    DBMS_CLOUD.PUT_OBJECT(
        credential_name => c_credential,
        object_uri      => c_target_uri,
        contents        => l_upload_blob
    );

    l_returned_blob := DBMS_CLOUD.GET_OBJECT(
        credential_name => c_credential,
        object_uri      => c_target_uri
    );

    DBMS_LOB.CREATETEMPORARY(l_returned_clob, TRUE);
    l_dest_offset  := 1;
    l_src_offset   := 1;
    l_lang_context := DBMS_LOB.DEFAULT_LANG_CTX;

    DBMS_LOB.CONVERTTOCLOB(
        dest_lob     => l_returned_clob,
        src_blob     => l_returned_blob,
        amount       => DBMS_LOB.LOBMAXSIZE,
        dest_offset  => l_dest_offset,
        src_offset   => l_src_offset,
        blob_csid    => NLS_CHARSET_ID('AL32UTF8'),
        lang_context => l_lang_context,
        warning      => l_warning
    );

    l_compare_result := DBMS_LOB.COMPARE(l_generated_clob, l_returned_clob);

    DBMS_OUTPUT.PUT_LINE('Returned BLOB size    : ' || DBMS_LOB.GETLENGTH(l_returned_blob) || ' bytes');
    DBMS_OUTPUT.PUT_LINE('Returned CLOB length  : ' || DBMS_LOB.GETLENGTH(l_returned_clob) || ' characters');
    DBMS_OUTPUT.PUT_LINE('DBMS_LOB.COMPARE      : ' || l_compare_result);
    DBMS_OUTPUT.PUT_LINE('Result                : ' || CASE WHEN l_compare_result = 0 THEN 'IDENTICAL' ELSE 'DIFFERENT' END);
    DBMS_OUTPUT.PUT_LINE('--- Returned text ---');
    DBMS_OUTPUT.PUT_LINE(DBMS_LOB.SUBSTR(l_returned_clob, 32767, 1));

    DBMS_LOB.FREETEMPORARY(l_generated_clob);
    DBMS_LOB.FREETEMPORARY(l_upload_blob);
    DBMS_LOB.FREETEMPORARY(l_returned_clob);

    IF DBMS_LOB.ISTEMPORARY(l_returned_blob) = 1 THEN
        DBMS_LOB.FREETEMPORARY(l_returned_blob);
    END IF;
END;
/
